-- begin PIZZA_PAYMENT
alter table PIZZA_PAYMENT add constraint FK_PIZZA_PAYMENT_ON_ORDER foreign key (ORDER_ID) references PIZZA_ORDER(ID)^
create index IDX_PIZZA_PAYMENT_ON_ORDER on PIZZA_PAYMENT (ORDER_ID)^
-- end PIZZA_PAYMENT
-- begin PIZZA_INGREDIENTS
alter table PIZZA_INGREDIENTS add constraint FK_PIZZA_INGREDIENTS_ON_PIZZA foreign key (PIZZA_ID) references PIZZA_PIZZA(ID)^
alter table PIZZA_INGREDIENTS add constraint FK_PIZZA_INGREDIENTS_ON_TOPINGS foreign key (TOPINGS_ID) references PIZZA_TOPINGS(ID)^
create index IDX_PIZZA_INGREDIENTS_ON_PIZZA on PIZZA_INGREDIENTS (PIZZA_ID)^
create index IDX_PIZZA_INGREDIENTS_ON_TOPINGS on PIZZA_INGREDIENTS (TOPINGS_ID)^
-- end PIZZA_INGREDIENTS

-- begin PIZZA_ORDER_ITEM
alter table PIZZA_ORDER_ITEM add constraint FK_PIZZA_ORDER_ITEM_ON_ORDER foreign key (ORDER_ID) references PIZZA_ORDER(ID)^
alter table PIZZA_ORDER_ITEM add constraint FK_PIZZA_ORDER_ITEM_ON_PIZZA foreign key (PIZZA_ID) references PIZZA_PIZZA(ID)^
create index IDX_PIZZA_ORDER_ITEM_ON_ORDER on PIZZA_ORDER_ITEM (ORDER_ID)^
create index IDX_PIZZA_ORDER_ITEM_ON_PIZZA on PIZZA_ORDER_ITEM (PIZZA_ID)^
-- end PIZZA_ORDER_ITEM
-- begin PIZZA_ORDER
alter table PIZZA_ORDER add constraint FK_PIZZA_ORDER_ON_DELIVERY_COURIER foreign key (DELIVERY_COURIER_ID) references SEC_USER(ID)^
create index IDX_PIZZA_ORDER_ON_DELIVERY_COURIER on PIZZA_ORDER (DELIVERY_COURIER_ID)^
-- end PIZZA_ORDER
