alter table PIZZA_INGREDIENTS add constraint FK_PIZZA_INGREDIENTS_ON_TOPINGS foreign key (TOPINGS_ID) references PIZZA_TOPINGS(ID);
create index IDX_PIZZA_INGREDIENTS_ON_TOPINGS on PIZZA_INGREDIENTS (TOPINGS_ID);
