alter table PIZZA_INGREDIENTS add constraint FK_PIZZA_INGREDIENTS_ON_PIZZA foreign key (PIZZA_ID) references PIZZA_PIZZA(ID);
create index IDX_PIZZA_INGREDIENTS_ON_PIZZA on PIZZA_INGREDIENTS (PIZZA_ID);
